import type { LocalDatabase } from '../platform/database.js';
import { newId, nowIso, queryOne, runOperation, runTransaction, safeJson } from './database.js';

export type LocationKind='home'|'neighborhood'|'cafe'|'restaurant'|'store'|'park'|'library'|'mall'|'transit'|'work'|'study'|'venue'|'outdoor'|'other';
export type LocationSource='builtin'|'generated'|'admin'|'conversation';
export type TravelMode='walk'|'bike'|'transit'|'car'|'unknown';
export interface LifeLocationRow{id:string;key:string|null;name:string;kind:LocationKind;city_id:string|null;city:string|null;region:string|null;country:string|null;time_zone:string|null;lat:number|null;lng:number|null;tags_json:string;indoor:number;visit_weight:number;source:LocationSource;active:number;created_at:string;updated_at:string;}
export interface LifeLocationInput{key?:string|null;name:string;kind:LocationKind;cityId?:string|null;city?:string|null;region?:string|null;country?:string|null;timeZone?:string|null;lat?:number|null;lng?:number|null;tags?:string[];indoor?:boolean;visitWeight?:number;source?:LocationSource;}
export interface LifeLocationStateRow{id:number;location_id:string;arrived_at:string;expected_leave_at:string|null;source_plan_id:string|null;source_activity_id:string|null;confidence:number;updated_at:string;}
export interface LifeLocationVisitRow{id:string;location_id:string;entered_at:string;left_at:string|null;source_plan_id:string|null;source_activity_id:string|null;created_at:string;}
export interface LifeLocationEdgeRow{from_id:string;to_id:string;travel_minutes:number;mode:TravelMode;}
export interface TravelStateRow{id:number;from_location_id:string;to_location_id:string;mode:TravelMode;started_at:string;expected_arrive_at:string;source_plan_id:string|null;source_activity_id:string|null;created_at:string;}
export interface LifeCityRow{id:string;key:string|null;name:string;region:string|null;country:string|null;time_zone:string;active:number;created_at:string;updated_at:string;}
export interface LifeCityInput{key?:string|null;name:string;region?:string|null;country?:string|null;timeZone?:string;active?:boolean;}

export class LocationRepo{
  constructor(readonly dbHandle:LocalDatabase,private readonly now:()=>Date=()=>new Date()){}
  async list(activeOnly=true):Promise<LifeLocationRow[]>{return await this.dbHandle.query(activeOnly?'SELECT * FROM life_locations WHERE active=1 ORDER BY visit_weight DESC,name':'SELECT * FROM life_locations ORDER BY visit_weight DESC,name');}
  async get(id:string):Promise<LifeLocationRow|undefined>{return await queryOne(this.dbHandle,'SELECT * FROM life_locations WHERE id=?',[id]);}
  async getByKey(key:string):Promise<LifeLocationRow|undefined>{return await queryOne(this.dbHandle,'SELECT * FROM life_locations WHERE key=? LIMIT 1',[key]);}
  async byCityId(cityId:string):Promise<LifeLocationRow[]>{return await this.dbHandle.query('SELECT * FROM life_locations WHERE city_id=? ORDER BY visit_weight DESC,name',[cityId]);}
  async create(input:LifeLocationInput):Promise<LifeLocationRow>{const ts=nowIso(this.now);const row:LifeLocationRow={id:newId('loc'),key:input.key??null,name:input.name,kind:input.kind,city_id:input.cityId??null,city:input.city??null,region:input.region??null,country:input.country??null,time_zone:input.timeZone??null,lat:input.lat??null,lng:input.lng??null,tags_json:JSON.stringify(input.tags??[]),indoor:input.indoor?1:0,visit_weight:input.visitWeight??1,source:input.source??'admin',active:1,created_at:ts,updated_at:ts};await this.dbHandle.run(`INSERT INTO life_locations(id,key,name,kind,city_id,city,region,country,time_zone,lat,lng,tags_json,indoor,visit_weight,source,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)`,[row.id,row.key,row.name,row.kind,row.city_id,row.city,row.region,row.country,row.time_zone,row.lat,row.lng,row.tags_json,row.indoor,row.visit_weight,row.source,row.created_at,row.updated_at]);return row;}
  async update(id:string,patch:Partial<LifeLocationInput>):Promise<LifeLocationRow|undefined>{const current=await this.get(id);if(!current)return undefined;const next:LifeLocationRow={...current,key:patch.key!==undefined?patch.key:current.key,name:patch.name??current.name,kind:patch.kind??current.kind,city_id:patch.cityId!==undefined?patch.cityId:current.city_id,city:patch.city!==undefined?patch.city:current.city,region:patch.region!==undefined?patch.region:current.region,country:patch.country!==undefined?patch.country:current.country,time_zone:patch.timeZone!==undefined?patch.timeZone:current.time_zone,lat:patch.lat!==undefined?patch.lat:current.lat,lng:patch.lng!==undefined?patch.lng:current.lng,tags_json:patch.tags?JSON.stringify(patch.tags):current.tags_json,indoor:patch.indoor===undefined?current.indoor:patch.indoor?1:0,visit_weight:patch.visitWeight??current.visit_weight,updated_at:nowIso(this.now)};await this.dbHandle.run(`UPDATE life_locations SET key=?,name=?,kind=?,city_id=?,city=?,region=?,country=?,time_zone=?,lat=?,lng=?,tags_json=?,indoor=?,visit_weight=?,updated_at=? WHERE id=?`,[next.key,next.name,next.kind,next.city_id,next.city,next.region,next.country,next.time_zone,next.lat,next.lng,next.tags_json,next.indoor,next.visit_weight,next.updated_at,id]);return next;}
  async deactivate(id:string):Promise<boolean>{return(await this.dbHandle.run('UPDATE life_locations SET active=0,updated_at=? WHERE id=?',[nowIso(this.now),id])).changes===1;}
  async currentState():Promise<LifeLocationStateRow|undefined>{return await queryOne(this.dbHandle,'SELECT * FROM life_location_state WHERE id=1');}
  async setState(input:{locationId:string;arrivedAt:string;expectedLeaveAt?:string|null;sourcePlanId?:string|null;sourceActivityId?:string|null;confidence?:number}):Promise<LifeLocationStateRow>{await this.dbHandle.run(`INSERT INTO life_location_state(id,location_id,arrived_at,expected_leave_at,source_plan_id,source_activity_id,confidence,updated_at) VALUES(1,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET location_id=excluded.location_id,arrived_at=excluded.arrived_at,expected_leave_at=excluded.expected_leave_at,source_plan_id=excluded.source_plan_id,source_activity_id=excluded.source_activity_id,confidence=excluded.confidence,updated_at=excluded.updated_at`,[input.locationId,input.arrivedAt,input.expectedLeaveAt??null,input.sourcePlanId??null,input.sourceActivityId??null,input.confidence??1,nowIso(this.now)]);return(await this.currentState())!;}
  async recentVisits(limit=20):Promise<LifeLocationVisitRow[]>{return await this.dbHandle.query('SELECT * FROM life_location_visits ORDER BY entered_at DESC LIMIT ?',[Math.max(1,Math.min(100,Math.trunc(limit)))]);}
  async visitOverlapping(startedAt:string,endedAt:string):Promise<LifeLocationVisitRow|undefined>{return await queryOne(this.dbHandle,'SELECT * FROM life_location_visits WHERE entered_at<=? AND COALESCE(left_at,?)>=? ORDER BY entered_at DESC LIMIT 1',[endedAt,endedAt,startedAt]);}
  async recentlyVisitedLocationIds(hours:number,nowMs=this.now().getTime()):Promise<string[]>{return(await this.dbHandle.query<{location_id:string}>('SELECT DISTINCT location_id FROM life_location_visits WHERE entered_at>? ORDER BY entered_at DESC',[new Date(nowMs-hours*3_600_000).toISOString()])).map(row=>row.location_id);}
  async recordVisit(input:{locationId:string;enteredAt:string;leftAt?:string|null;sourcePlanId?:string|null;sourceActivityId?:string|null}):Promise<LifeLocationVisitRow>{const row:LifeLocationVisitRow={id:newId('lvisit'),location_id:input.locationId,entered_at:input.enteredAt,left_at:input.leftAt??null,source_plan_id:input.sourcePlanId??null,source_activity_id:input.sourceActivityId??null,created_at:nowIso(this.now)};await this.dbHandle.run('INSERT INTO life_location_visits(id,location_id,entered_at,left_at,source_plan_id,source_activity_id,created_at) VALUES(?,?,?,?,?,?,?)',[row.id,row.location_id,row.entered_at,row.left_at,row.source_plan_id,row.source_activity_id,row.created_at]);return row;}
  async closeOpenVisits(locationId:string,leftAt:string):Promise<number>{return(await this.dbHandle.run('UPDATE life_location_visits SET left_at=? WHERE location_id=? AND left_at IS NULL',[leftAt,locationId])).changes;}
  async edge(fromId:string,toId:string):Promise<LifeLocationEdgeRow|undefined>{return await queryOne(this.dbHandle,'SELECT * FROM life_location_edges WHERE from_id=? AND to_id=?',[fromId,toId]);}
  async edgesFrom(fromId:string):Promise<LifeLocationEdgeRow[]>{return await this.dbHandle.query('SELECT * FROM life_location_edges WHERE from_id=?',[fromId]);}
  async saveEdge(fromId:string,toId:string,travelMinutes:number,mode:TravelMode='walk'):Promise<void>{await this.dbHandle.run('INSERT INTO life_location_edges(from_id,to_id,travel_minutes,mode) VALUES(?,?,?,?) ON CONFLICT(from_id,to_id) DO UPDATE SET travel_minutes=excluded.travel_minutes,mode=excluded.mode',[fromId,toId,Math.max(1,Math.round(travelMinutes)),mode]);}
  async deleteEdgesTo(locationId:string):Promise<number>{return(await this.dbHandle.run('DELETE FROM life_location_edges WHERE from_id=? OR to_id=?',[locationId,locationId])).changes;}
  async currentTravel():Promise<TravelStateRow|undefined>{return await queryOne(this.dbHandle,'SELECT * FROM travel_state WHERE id=1');}
  async setTravel(input:{fromLocationId:string;toLocationId:string;mode:TravelMode;startedAt:string;expectedArriveAt:string;sourcePlanId?:string|null;sourceActivityId?:string|null}):Promise<TravelStateRow>{await this.dbHandle.run(`INSERT INTO travel_state(id,from_location_id,to_location_id,mode,started_at,expected_arrive_at,source_plan_id,source_activity_id,created_at) VALUES(1,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET from_location_id=excluded.from_location_id,to_location_id=excluded.to_location_id,mode=excluded.mode,started_at=excluded.started_at,expected_arrive_at=excluded.expected_arrive_at,source_plan_id=excluded.source_plan_id,source_activity_id=excluded.source_activity_id,created_at=excluded.created_at`,[input.fromLocationId,input.toLocationId,input.mode,input.startedAt,input.expectedArriveAt,input.sourcePlanId??null,input.sourceActivityId??null,nowIso(this.now)]);return(await this.currentTravel())!;}
  async setKey(id:string,key:string):Promise<void>{await this.dbHandle.run('UPDATE life_locations SET key=?,updated_at=? WHERE id=?',[key,nowIso(this.now),id]);}
  async updateCityId(id:string,cityId:string):Promise<void>{await this.dbHandle.run('UPDATE life_locations SET city_id=?,updated_at=? WHERE id=?',[cityId,nowIso(this.now),id]);}
  async clearTravel():Promise<void>{await this.dbHandle.run('DELETE FROM travel_state WHERE id=1');}
}

export class LifeCityRepo{
  constructor(private readonly db:LocalDatabase,private readonly now:()=>Date=()=>new Date()){}
  async list():Promise<LifeCityRow[]>{return await this.db.query('SELECT * FROM life_cities ORDER BY active DESC,created_at,name');}
  async get(id:string):Promise<LifeCityRow|undefined>{return await queryOne(this.db,'SELECT * FROM life_cities WHERE id=?',[id]);}
  async getByKey(key:string):Promise<LifeCityRow|undefined>{return await queryOne(this.db,'SELECT * FROM life_cities WHERE key=? LIMIT 1',[key]);}
  async activeCity():Promise<LifeCityRow|undefined>{return await queryOne(this.db,'SELECT * FROM life_cities WHERE active=1 LIMIT 1');}
  async create(input:LifeCityInput):Promise<LifeCityRow>{const ts=nowIso(this.now);const wantActive=input.active??!(await this.activeCity());const row:LifeCityRow={id:newId('city'),key:input.key??null,name:input.name,region:input.region??null,country:input.country??null,time_zone:input.timeZone??'Asia/Shanghai',active:wantActive?1:0,created_at:ts,updated_at:ts};const operations=[];if(wantActive)operations.push(runOperation('UPDATE life_cities SET active=0,updated_at=? WHERE active=1',[ts]));operations.push(runOperation('INSERT INTO life_cities(id,key,name,region,country,time_zone,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',[row.id,row.key,row.name,row.region,row.country,row.time_zone,row.active,row.created_at,row.updated_at]));await runTransaction(this.db,operations);return row;}
  async update(id:string,patch:Partial<LifeCityInput>):Promise<LifeCityRow|undefined>{const current=await this.get(id);if(!current)return undefined;const ts=nowIso(this.now);const next:LifeCityRow={...current,key:patch.key!==undefined?patch.key:current.key,name:patch.name??current.name,region:patch.region!==undefined?patch.region:current.region,country:patch.country!==undefined?patch.country:current.country,time_zone:patch.timeZone??current.time_zone,active:patch.active===undefined?current.active:patch.active?1:0,updated_at:ts};const operations=[];if(next.active)operations.push(runOperation('UPDATE life_cities SET active=0,updated_at=? WHERE active=1 AND id<>?',[ts,id]));operations.push(runOperation('UPDATE life_cities SET key=?,name=?,region=?,country=?,time_zone=?,active=?,updated_at=? WHERE id=?',[next.key,next.name,next.region,next.country,next.time_zone,next.active,ts,id]));operations.push(runOperation(`UPDATE life_cities SET active=1,updated_at=? WHERE id=(SELECT id FROM life_cities WHERE id<>? ORDER BY created_at LIMIT 1) AND NOT EXISTS(SELECT 1 FROM life_cities WHERE active=1)`,[ts,id]));await runTransaction(this.db,operations);return await this.get(id);}
  async deactivate(id:string):Promise<boolean>{const current=await this.get(id);if(!current)return false;const fallback=await queryOne<{id:string}>(this.db,'SELECT id FROM life_cities WHERE id<>? ORDER BY created_at LIMIT 1',[id]);if(current.active===1&&!fallback)return false;const ts=nowIso(this.now);const operations=[runOperation('UPDATE life_cities SET active=0,updated_at=? WHERE id=?',[ts,id])];if(current.active===1&&fallback)operations.push(runOperation('UPDATE life_cities SET active=1,updated_at=? WHERE id=?',[ts,fallback.id]));await runTransaction(this.db,operations);return true;}
  async setActiveCity(id:string):Promise<LifeCityRow|undefined>{if(!await this.get(id))return undefined;const ts=nowIso(this.now);await runTransaction(this.db,[runOperation('UPDATE life_cities SET active=0,updated_at=? WHERE active=1',[ts]),runOperation('UPDATE life_cities SET active=1,updated_at=? WHERE id=?',[ts,id])]);return await this.get(id);}
}

export function toLifeLocation(row:LifeLocationRow){return{id:row.id,key:row.key,name:row.name,kind:row.kind,cityId:row.city_id,city:row.city,region:row.region,country:row.country,timeZone:row.time_zone,lat:row.lat,lng:row.lng,tags:safeJson<string[]>(row.tags_json,[]),indoor:row.indoor===1,visitWeight:row.visit_weight,source:row.source,active:row.active===1};}
