import type { LocalDatabase } from '../platform/database.js';
import { nowIso, runOperation, runTransaction } from './database.js';

export interface MetricDailyRow{date:string;category:string;metric:string;sum_value:number;count:number;min_value:number|null;max_value:number|null;last_updated:string;}
export interface MetricAggregate{category:string;metric:string;sum:number;count:number;avg:number;}
export interface MetricsDistribution{category:string;metric:string;count:number;sum:number;min:number;max:number;mean:number;p50:number;p95:number;}
export interface MetricExportRow{date:string;category:string;metric:string;count:number;sum:number;min:number;max:number;}

export class MetricsRepo{
  constructor(private readonly db:LocalDatabase,private readonly now:()=>Date=()=>new Date()){}
  async record(category:string,metric:string,value:number,day:string):Promise<void>{const bucket=Math.round(value*100)/100;await runTransaction(this.db,[runOperation(`INSERT INTO metric_daily(date,category,metric,sum_value,count,min_value,max_value,last_updated) VALUES(?,?,?,?,1,?,?,?) ON CONFLICT(date,category,metric) DO UPDATE SET sum_value=sum_value+excluded.sum_value,count=count+1,min_value=MIN(COALESCE(min_value,excluded.min_value),excluded.min_value),max_value=MAX(COALESCE(max_value,excluded.max_value),excluded.max_value),last_updated=excluded.last_updated`,[day,category,metric,value,value,value,nowIso(this.now)]),runOperation(`INSERT INTO metric_distributions(date,category,metric,bucket,count) VALUES(?,?,?,?,1) ON CONFLICT(date,category,metric,bucket) DO UPDATE SET count=count+1`,[day,category,metric,bucket])]);}
  async aggregates(fromDate:string,toDate:string):Promise<MetricAggregate[]>{const rows=await this.db.query<{category:string;metric:string;sum:number;count:number}>('SELECT category,metric,SUM(sum_value) sum,SUM(count) count FROM metric_daily WHERE date BETWEEN ? AND ? GROUP BY category,metric ORDER BY category,metric',[fromDate,toDate]);return rows.map(row=>({...row,avg:row.count>0?row.sum/row.count:0}));}
  async daily(fromDate:string,toDate:string):Promise<MetricDailyRow[]>{return await this.db.query('SELECT * FROM metric_daily WHERE date BETWEEN ? AND ? ORDER BY date,category,metric',[fromDate,toDate]);}
  async categories():Promise<string[]>{return(await this.db.query<{category:string}>('SELECT DISTINCT category FROM metric_daily ORDER BY category')).map(row=>row.category);}
  async distributions(fromDate:string,toDate:string):Promise<MetricsDistribution[]>{const aggregates=await this.db.query<{category:string;metric:string;sum:number;count:number;min:number;max:number}>(`SELECT category,metric,SUM(sum_value) sum,SUM(count) count,MIN(COALESCE(min_value,0)) min,MAX(COALESCE(max_value,0)) max FROM metric_daily WHERE date BETWEEN ? AND ? GROUP BY category,metric ORDER BY category,metric`,[fromDate,toDate]);const histogram=await this.db.query<{category:string;metric:string;bucket:number;count:number}>(`SELECT category,metric,bucket,SUM(count) count FROM metric_distributions WHERE date BETWEEN ? AND ? GROUP BY category,metric,bucket ORDER BY category,metric,bucket`,[fromDate,toDate]);const byKey=new Map<string,Array<{bucket:number;count:number}>>();for(const row of histogram){const key=`${row.category}\0${row.metric}`;const list=byKey.get(key)??[];list.push({bucket:row.bucket,count:row.count});byKey.set(key,list);}return aggregates.map(row=>{const buckets=byKey.get(`${row.category}\0${row.metric}`)??[];return{...row,mean:row.count>0?row.sum/row.count:0,p50:percentileAt(buckets,0.5),p95:percentileAt(buckets,0.95)};});}
  async exportRows(fromDate:string,toDate:string):Promise<MetricExportRow[]>{return await this.db.query(`SELECT date,category,metric,sum_value sum,count,COALESCE(min_value,0) min,COALESCE(max_value,0) max FROM metric_daily WHERE date BETWEEN ? AND ? ORDER BY date,category,metric`,[fromDate,toDate]);}
}
function percentileAt(buckets:Array<{bucket:number;count:number}>,q:number):number{const total=buckets.reduce((sum,item)=>sum+item.count,0);if(total<=0)return 0;const target=total*q;let cumulative=0;for(const item of buckets){cumulative+=item.count;if(cumulative>=target)return item.bucket;}return buckets.at(-1)?.bucket??0;}
