import type { LocalDatabase } from '../platform/database.js';
import { clampInteger, newId, nowIso, queryOne } from './database.js';
export type MomentImageKind='pov'|'selfie';
export interface MomentRow{id:string;candidate_id:string;text:string;image_media_id:string|null;image_kind:MomentImageKind|null;activity:string;location_id:string|null;location_name:string|null;city:string|null;weather_condition:string|null;temperature_c:number|null;liked:number;created_at:string;topic_key:string|null;source_event_id:string|null;status:'pending'|'published'|'suppressed'|'failed';shared_at:string|null;updated_at:string|null;}
export interface CreateMomentInput{candidateId:string;text:string;imageMediaId?:string|null;imageKind?:MomentImageKind|null;activity:string;locationId?:string|null;locationName?:string|null;city?:string|null;weatherCondition?:string|null;temperatureC?:number|null;createdAt?:string;topicKey?:string|null;sourceEventId?:string|null;status?:MomentRow['status'];}
export class MomentRepo{
  constructor(private readonly db:LocalDatabase,private readonly now:()=>Date=()=>new Date()){}
  async create(input:CreateMomentInput):Promise<MomentRow>{const timestamp=input.createdAt??nowIso(this.now);const row:MomentRow={id:newId('moment'),candidate_id:input.candidateId,text:input.text.trim(),image_media_id:input.imageMediaId??null,image_kind:input.imageKind??null,activity:input.activity,location_id:input.locationId??null,location_name:input.locationName??null,city:input.city??null,weather_condition:input.weatherCondition??null,temperature_c:input.temperatureC??null,liked:0,created_at:timestamp,topic_key:input.topicKey??null,source_event_id:input.sourceEventId??null,status:input.status??'published',shared_at:(input.status??'published')==='published'?timestamp:null,updated_at:timestamp};await this.db.run(`INSERT INTO moments(id,candidate_id,text,image_media_id,image_kind,activity,location_id,location_name,city,weather_condition,temperature_c,liked,created_at,topic_key,source_event_id,status,shared_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[row.id,row.candidate_id,row.text,row.image_media_id,row.image_kind,row.activity,row.location_id,row.location_name,row.city,row.weather_condition,row.temperature_c,row.liked,row.created_at,row.topic_key,row.source_event_id,row.status,row.shared_at,row.updated_at]);return row;}
  async get(id:string):Promise<MomentRow|undefined>{return await queryOne(this.db,'SELECT * FROM moments WHERE id=?',[id]);}
  async latest():Promise<MomentRow|undefined>{return await queryOne(this.db,"SELECT * FROM moments WHERE status='published' ORDER BY created_at DESC LIMIT 1");}
  async list(limit=50):Promise<MomentRow[]>{return await this.db.query("SELECT * FROM moments WHERE status='published' ORDER BY created_at DESC LIMIT ?",[clampInteger(limit,1,200)]);}
  async setLiked(id:string,liked:boolean):Promise<MomentRow|undefined>{const changed=(await this.db.run('UPDATE moments SET liked=?,updated_at=? WHERE id=?',[liked?1:0,nowIso(this.now),id])).changes;return changed?await this.get(id):undefined;}
}
